# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        stages: [pre-push]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   stages: [pre-commit, pre-push, pre-merge-commit, post-merge, pre-rebase]
        id: coverage
        name: coverage-check
        entry: "pytest --cov=src -n=auto"
        language: system
        pass_filenames: false
        always_run: true
        verbosse: true
    -   stages: [pre-commit, pre-push, pre-merge-commit, post-merge, pre-rebase]
        id: coverage-badge
        name: coverage-badge
        entry: "coverage-badge -fo media/coverage.svg"
        language: system
        pass_filenames: false
    -   id: pre-wer
        name: create_txt
        always_run: true
        entry: python src/swescribe/srt_to_txt.py
        language: system
        pass_filenames: false
    -   id: wer
        name: calculate-wer
        always_run: true
        entry: python src/swescribe/wer.py
        language: system
        pass_filenames: false
