name: Black and Isort

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install black and isort
        run: |
          python -m pip install -U pip
          python -m pip install black isort
      - name: Run black
        run: |
          black .
      - name: Run isort
        run: |
          isort .
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'CI: lint python files'
          add: '*py'
