name: Calculate WER

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'
      - name: Install packages
        run: |
          python -m pip install -U pip
          python -m pip install pandas jiwer
          python -m pip install -e .
      - name: Convert srt to txt
        run: |
          python ./src/swescribe/srt_to_txt.py
      - name: Calculate WER
        run: |
          python ./src/swescribe/wer.py
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'CI: Calculate WER'
          add: '*csv data/txt_output/'
